server:
  build: ./server
  ports:
    - "80:80"
    - "3000:3000"
  links:
    - db
    - memcached
    - elasticsearch
  volumes:
    - ./src/zendphp/public:/var/www/zendphp/public

db:
  build: ./db
  environment:
    MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
    MYSQL_DATABASE: zendphp
    MYSQL_USER: zendphp
    MYSQL_PASSWORD: zendphp
    MYSQL_HOST: ""

  mem_limit: 1000000000
  volumes:
    - ./db/init.d:/docker-entrypoint-initdb.d
  ports:
    - "33333:3306"

elasticsearch:
  image: "elasticsearch:1.3"

memcached:
  image: memcached
