server:
    build: ./server
    ports:
        - "80:80"
        - "3000:3000"
    links:
        - mysql
        - memcached
    volumes:
        - ./var/www/html:/var/www/html

mysql:
    build: ./db
    environment:
        - MYSQL_ROOT_PASSWORD=lecaoquochung
        - MYSQL_DATABASE=zendphp
        - MYSQL_USER=zendphp
        - MYSQL_PASSWORD=zendphp
    mem_limit: 1000000000
    volumes:
        - ./db/init.d:/docker-entrypoint-initdb.d
    ports:
        - "3306:3306"

memcached:
  image: memcached
